### ISSUE TITLE
works on play-1.2.2?

### ISSUE THREAD

**Issue by potatosh** [pepite/play--database#7]
Does db-1.1.1 works completely on play-1.2.2, or is there the release plan of db-1.2?

**Comment by pepite** [comment]
Hi,

It should work. If not can you report a bug? 

Thanks

Nicolas

**Comment by dsheng** [comment]
Hi Nicolas,

db-1.1.1 failed to work in play-1.2.2, exceptions raised as the follow:

Exception in thread "main" java.lang.NoSuchMethodError: org.hibernate.mapping.SimpleValue.<init>(Lorg/hibernate/mapping/Table;)V

Thanks

Dsheng

**Comment by dsheng** [comment]
Hi All,

I resolved this issue for play-1.2.2

1, fixed hibernate-tools JavaTypeFromValueVisitor.java 's method as follow: 
 public Object accept(OneToMany value) {
    //return value.getAssociatedClass().getClassName();
    return value.getReferencedEntityName();
  }

2, copy hibernate3.jar to module/db-1.1.1/lib

that's it, works for me.

**Comment by pepite** [comment]
cool, I need to upgrade the module then. Thanks

**Comment by ghost** [comment]
The module still not updated.

**Comment by Cwellan** [comment]
Hi all,

Anyone has a fix ?
I encountered the same error...

dsheng, do you have a modified hibernate-tools that works ?

Thanks in advance !

**Comment by dsheng** [comment]
Okay, I fork it at https://github.com/dsheng/play--database ,  try it.

**Comment by pepite** [comment]
Do you want to be the official maintainer of this module? I can add you here and you can then update the code base and also update the module on the official playframework.org module repo.

**Comment by Cwellan** [comment]
Dsheng, thanks a lot, i'll try !

**Comment by dsheng** [comment]
Hi Pepite, no problem, I'd like to maintain it if you want.

**Comment by pepite** [comment]
Thanks, I added you to the repo so you should be able to push/pull do whatever you want here. I now need your open id and full name to add you as the official maintainer in the module repo. Can you send me an email with this info (leroux.nicolas@gmail.com). Thanks

**Comment by Cwellan** [comment]
Dsheng, it seems not work. When i had hibernate3.jar, an error occurs... 

23:13:55,406 INFO  ~ Starting C:\Users\X\Projet
23:13:55,411 INFO  ~ Module db is available (C:\play-1.2.4\modules\db-1.1.1)
23:13:56,043 WARN  ~ You're running Play! in DEV mode
23:13:56,470 INFO  ~ Iterating on arguments, args.length = 0
23:13:56,470 INFO  ~ Importer will use db.driver = com.mysql.jdbc.Driver
23:13:56,470 INFO  ~ Importer will use db.user = user
23:13:56,471 INFO  ~ Importer will use db.password
23:13:56,471 INFO  ~ Importer will use db.url = jdbc:mysql://localhost/test
23:13:57,913 INFO  ~ DB metadata reading done.
23:13:57,913 INFO  ~ POJO generation enabled.
23:13:57,938 INFO  ~ Starting POJO Exporter ...
23:13:58,223 ERROR ~

**Comment by dsheng** [comment]
Hi Cwellan, I update hibernate-tools.jar and some pojo ftl files, you can test it again, I only test it in play 1.2.3, It works!.

**Comment by Cwellan** [comment]
Hi,

Thank you, i'll test with play 1.2.4 first !

**Comment by Cwellan** [comment]
OH MY GOD ! THAT WORKS !!!!! 
You save my life ! =D
You're an amazing developper !
